"""wasmhost: run WebAssembly from CPython, PyPy and Pythonista, with the JavaScript WebAssembly API.

`Module`, `Instance`, `Memory` and `Global` run on a backend: JavaScriptCore's `JSContext` (Pythonista on iOS),
WebKitGTK's JavaScriptCore (Linux), Node, or a native runtime (wasmtime, wasm3). Plain Python, no dependencies,
no C extension of its own.
"""

from ._api import (
    Batch,
    CompileError,
    Function,
    Global,
    Instance,
    Instantiated,
    LinkError,
    Memory,
    Module,
    OutOfFuel,
    Ref,
    Table,
    Timeout,
    Trap,
    WasmError,
    close,
    compile,
    get_backend,
    instantiate,
    instantiate_sync,
    set_backend,
    validate,
)
from ._backend import Backend
from ._binary import (
    ExportDescriptor,
    FuncType,
    GlobalType,
    ImportDescriptor,
    MemoryType,
    TableType,
    ValueType,
    f32,
    f64,
    i32,
    i64,
)
from ._js import BunBackend, GIJavaScriptCoreBackend, JSBackend, JSContextBackend, NodeBackend
from ._jsc import JSCBackend
from ._native import Wasm3Backend, WasmtimeBackend
from ._registry import AUTO_ORDER, BACKENDS, JS_AUTO_ORDER, JS_BACKENDS, default_backend
from ._selftest import selftest

__all__ = (
    "AUTO_ORDER",
    "BACKENDS",
    "JS_AUTO_ORDER",
    "JS_BACKENDS",
    "Backend",
    "Batch",
    "BunBackend",
    "CompileError",
    "ExportDescriptor",
    "FuncType",
    "Function",
    "GIJavaScriptCoreBackend",
    "Global",
    "GlobalType",
    "ImportDescriptor",
    "Instance",
    "Instantiated",
    "JSBackend",
    "JSCBackend",
    "JSContextBackend",
    "LinkError",
    "Memory",
    "MemoryType",
    "Module",
    "NodeBackend",
    "Ref",
    "Table",
    "TableType",
    "ValueType",
    "OutOfFuel",
    "Timeout",
    "Trap",
    "Wasm3Backend",
    "WasmError",
    "WasmtimeBackend",
    "close",
    "compile",
    "instantiate_sync",
    "default_backend",
    "get_backend",
    "instantiate",
    "instantiate_sync",
    "selftest",
    "set_backend",
    "validate",
    "f32",
    "f64",
    "i32",
    "i64",
)
